# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Gitea systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ gitea_identifier }}.service"
  register: gitea_service_stat

- name: Uninstall Gitea systemd services and files
  when: gitea_service_stat.stat.exists | bool
  block:
    - name: Ensure Gitea systemd service is stopped
      ansible.builtin.service:
        name: "{{ gitea_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Gitea systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ gitea_identifier }}.service"
        state: absent

    - name: Ensure Gitea path does not exist
      ansible.builtin.file:
        path: "{{ gitea_base_path }}"
        state: absent
